In [2]:
import tensorflow as tf

In [31]:
idx = tf.range(10)
idx = tf.random.shuffle(idx)

print(idx)

tf.Tensor([7 8 9 3 1 4 2 5 0 6], shape=(10,), dtype=int32)


In [32]:
a = tf.random.normal([10, 784])
b = tf.random.uniform([10], maxval=10, dtype=tf.int32)

print(a)
print(b)

tf.Tensor(
[[-0.990611   -0.6115907  -0.18459266 ...  0.59540576 -0.3611763
  -0.42478624]
 [-0.9889593   0.10148653  0.7698524  ...  0.06171652 -1.4275547
  -0.7721569 ]
 [-0.25397608  0.2242649  -0.9363989  ...  1.9984083  -0.7647652
   0.5235895 ]
 ...
 [-0.9993459  -1.2953984   1.1052573  ... -0.01896489  0.8950745
   1.3507744 ]
 [-0.13642244 -0.06731     1.6737901  ...  1.1343237  -0.6692499
  -0.93689334]
 [-0.11224463  2.5040717   2.4233189  ...  0.61712986  1.3114134
  -0.19155532]], shape=(10, 784), dtype=float32)
tf.Tensor([4 7 4 8 1 0 1 1 3 5], shape=(10,), dtype=int32)


In [39]:
a = tf.gather(a, idx)
a

<tf.Tensor: id=220, shape=(10, 784), dtype=float32, numpy=
array([[-0.9993459 , -1.2953984 ,  1.1052573 , ..., -0.01896489,
         0.8950745 ,  1.3507744 ],
       [-0.13642244, -0.06731   ,  1.6737901 , ...,  1.1343237 ,
        -0.6692499 , -0.93689334],
       [-0.11224463,  2.5040717 ,  2.4233189 , ...,  0.61712986,
         1.3114134 , -0.19155532],
       ...,
       [-0.36778873, -1.5633614 , -0.84105694, ..., -0.7960318 ,
         0.26168627, -0.22506562],
       [-0.990611  , -0.6115907 , -0.18459266, ...,  0.59540576,
        -0.3611763 , -0.42478624],
       [-0.7932905 , -0.75275314, -0.9074838 , ..., -2.324202  ,
         0.9194799 , -1.2222632 ]], dtype=float32)>

In [41]:
b = tf.gather(b, idx)
b

<tf.Tensor: id=224, shape=(10,), dtype=int32, numpy=array([0, 4, 1, 8, 3, 7, 5, 1, 1, 4], dtype=int32)>